//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbumDownloader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlbumDownloader.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please authorize in VK to proceed..
        /// </summary>
        internal static string AuthorizationDialogClosedByUserString {
            get {
                return ResourceManager.GetString("AuthorizationDialogClosedByUserString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authorize user! {0}.
        /// </summary>
        internal static string AuthorizationFailedErroString {
            get {
                return ResourceManager.GetString("AuthorizationFailedErroString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed successfully!.
        /// </summary>
        internal static string DownloadCompletedString {
            get {
                return ResourceManager.GetString("DownloadCompletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErrorTitleString {
            get {
                return ResourceManager.GetString("ErrorTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to receive profile info!.
        /// </summary>
        internal static string ReceivingProfileInfoFailedErrorString {
            get {
                return ResourceManager.GetString("ReceivingProfileInfoFailedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request took too long ( &gt; {0}s). Aborting..
        /// </summary>
        internal static string RequestCanceledErrorString {
            get {
                return ResourceManager.GetString("RequestCanceledErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed. {0}.
        /// </summary>
        internal static string RequestFailedErrorString {
            get {
                return ResourceManager.GetString("RequestFailedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize received response!.
        /// </summary>
        internal static string ResponseDeserializationFailedErrorString {
            get {
                return ResourceManager.GetString("ResponseDeserializationFailedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string SuccessTitleString {
            get {
                return ResourceManager.GetString("SuccessTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session time has expired please log in anew!.
        /// </summary>
        internal static string TokenExpiredErrorString {
            get {
                return ResourceManager.GetString("TokenExpiredErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total photos download progress.
        /// </summary>
        internal static string TotalPhotosDownloadProgressString {
            get {
                return ResourceManager.GetString("TotalPhotosDownloadProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Progress.
        /// </summary>
        internal static string TotalProgressString {
            get {
                return ResourceManager.GetString("TotalProgressString", resourceCulture);
            }
        }
    }
}
